//! The versioned wire contract between the jobs Worker (TypeScript, PR F/H) and
//! this processor.
//!
//! Everything a caller needs to know is a constant or a struct in this file, and
//! the numeric limits are enforced in code rather than described in a comment:
//! [`Limits`] is what `/health` reports, [`crate::http`] refuses a body larger
//! than [`Limits::max_input_bytes`] while it reads, and [`crate::encode`]
//! refuses output larger than [`Limits::max_output_bytes`] before validating it.
//!
//! Frozen names, coordinated with PR F. Changing one is a protocol change: bump
//! [`PROTOCOL_ID`], add a golden fixture, and change both sides together.
//!
//! * protocol `sample-v1` — request/response framing and metadata shape.
//! * preset `demo-180p-v1` — the only accepted encode configuration.
//! * fixture `sample-v1` — the synthetic 3 s 320x180 input, generated by
//!   `starter-media fixture` (see `fixtures/media/README.md`).
//!
//! `fixture` and `protocol` are the same string because they were frozen
//! together: the synthetic input and the framing that carries it are one
//! revision. If they ever move apart they become two constants, not two
//! spellings of one.

use serde::{Deserialize, Serialize};

/// Wire protocol version. Sent as `x-protocol`; reported by `/health`.
pub const PROTOCOL_ID: &str = "sample-v1";

/// The only preset this build accepts.
pub const PRESET_ID: &str = "demo-180p-v1";

/// The synthetic input identity admitted by the preset.
pub const FIXTURE_ID: &str = "sample-v1";

/// Request header naming the protocol. Optional; absent means [`PROTOCOL_ID`].
pub const HEADER_PROTOCOL: &str = "x-protocol";
/// Request header naming the preset. Required.
pub const HEADER_PRESET: &str = "x-preset";
/// Request header naming the attempt. Required; echoed in the response.
pub const HEADER_ATTEMPT: &str = "x-attempt-id";

/// Response header carrying the SHA-256 of the exact output bytes, lowercase hex.
pub const HEADER_OUTPUT_SHA256: &str = "x-output-sha256";
/// Response header carrying the output length in bytes.
pub const HEADER_OUTPUT_BYTES: &str = "x-output-bytes";
/// Response header carrying the probed duration in milliseconds.
pub const HEADER_OUTPUT_DURATION_MS: &str = "x-output-duration-ms";
/// Response header carrying the probed video codec name (`h264`).
pub const HEADER_OUTPUT_CODEC: &str = "x-output-codec";
/// Response header carrying `WxH` as probed from the output.
pub const HEADER_OUTPUT_DIMENSIONS: &str = "x-output-dimensions";

/// Upper bound on the request body, enforced while reading.
pub const MAX_INPUT_BYTES: u64 = 5 * 1024 * 1024;

/// Upper bound on the encoded output, enforced before validation.
pub const MAX_OUTPUT_BYTES: u64 = 10 * 1024 * 1024;

/// Wall-clock budget for one FFmpeg invocation.
pub const ENCODE_DEADLINE_MS: u64 = 120_000;

/// Wall-clock budget for the FFprobe validation that follows an encode. Short on
/// purpose: the output is local and small, so a slow probe means a broken
/// process, not slow work.
pub const PROBE_DEADLINE_MS: u64 = 20_000;

/// Encoding threads handed to FFmpeg.
pub const MAX_ENCODE_THREADS: u32 = 2;

/// Concurrent encodes this container accepts. One, because the container has one
/// measured CPU budget and a second concurrent FFmpeg would double peak memory
/// for a workload that is already the demo's worst case. See README "Profile".
pub const MAX_CONCURRENT_ENCODES: u32 = 1;

/// Longest accepted `x-attempt-id`.
pub const MAX_ATTEMPT_ID_LEN: usize = 128;

/// Longest accepted HTTP request head (request line plus headers), in bytes.
pub const MAX_REQUEST_HEAD_BYTES: usize = 16 * 1024;

/// Bytes of FFmpeg stderr retained for an operator. The reader keeps draining
/// past this bound so the child never blocks on a full pipe, and counts the
/// bytes it dropped.
pub const STDERR_KEEP_BYTES: usize = 8 * 1024;

/// Concurrent HTTP connections accepted. Small because the container serves one
/// Durable Object client; it is a bound, not a throughput setting.
pub const MAX_CONNECTIONS: u32 = 32;

/// Upper bound on the FFprobe JSON document this crate will parse for one file.
/// A ≤10 MiB MP4's stream list is tens of kilobytes; 1 MiB is two orders of
/// magnitude of headroom and still a hard bound on the allocation.
pub const MAX_PROBE_JSON_BYTES: usize = 1024 * 1024;

/// How long a refused request's connection is drained before the socket is
/// closed.
///
/// A request refused before its body was read leaves the client still sending.
/// Closing on top of unread bytes makes the kernel send RST and the client never
/// sees the status it was owed, so the response is followed by a bounded drain.
pub const DRAIN_GRACE_MS: u64 = 2_000;

/// Upper bound on bytes drained from a refused request. Past this the socket is
/// closed even if the peer is still writing.
pub const DRAIN_MAX_BYTES: u64 = 32 * 1024 * 1024;

/// How long the process waits for in-flight encodes after SIGTERM before it
/// stops waiting and exits anyway. The child is killed and its temp directory
/// removed by the encode path itself, so this only bounds the exit delay.
pub const SHUTDOWN_GRACE_MS: u64 = 10_000;

/// The default listen port. Cloudflare Containers route to the container's
/// port; 8080 is the platform's documented default.
pub const DEFAULT_PORT: u16 = 8080;

/// Every bound the server enforces, as reported by `/health`.
///
/// This is the single source of the numbers: the parser, the encoder and the
/// health response all read these constants, so a limit cannot be tightened in
/// one place and advertised as unchanged in another.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct Limits {
    pub max_input_bytes: u64,
    pub max_output_bytes: u64,
    pub encode_deadline_ms: u64,
    pub probe_deadline_ms: u64,
    pub max_encode_threads: u32,
    pub max_concurrent_encodes: u32,
    pub max_attempt_id_len: usize,
    pub stderr_keep_bytes: usize,
}

impl Limits {
    /// The bounds this build enforces. `const` so a test can assert the health
    /// document against the compiler's view of them.
    pub const CURRENT: Limits = Limits {
        max_input_bytes: MAX_INPUT_BYTES,
        max_output_bytes: MAX_OUTPUT_BYTES,
        encode_deadline_ms: ENCODE_DEADLINE_MS,
        probe_deadline_ms: PROBE_DEADLINE_MS,
        max_encode_threads: MAX_ENCODE_THREADS,
        max_concurrent_encodes: MAX_CONCURRENT_ENCODES,
        max_attempt_id_len: MAX_ATTEMPT_ID_LEN,
        stderr_keep_bytes: STDERR_KEEP_BYTES,
    };
}

/// What this build can do, for a caller deciding whether to call it at all.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct HealthDocument {
    /// Crate version plus the git revision when the build knows one. The
    /// revision is a build-time value (`BUILD_GIT_REVISION`), not a guess made
    /// at runtime.
    pub release: String,
    pub protocol: String,
    pub presets: Vec<PresetSummary>,
    pub fixture: String,
    pub limits: Limits,
}

/// One accepted preset, described well enough for a caller to display it.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct PresetSummary {
    pub id: String,
    pub width: u32,
    pub height: u32,
    pub fps: u32,
    pub video_codec: String,
    pub audio_codec: Option<String>,
    pub container: String,
}

/// The metadata a successful `/encode` reports about bytes it produced.
///
/// Also serialized as a standalone document (`fixtures/protocol/
/// encode-success.v1.json`) so the TypeScript side can type-check a value it can
/// compare, rather than a set of header strings.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct EncodeSuccessDocument {
    pub protocol: String,
    pub preset: String,
    pub attempt_id: String,
    pub output_bytes: u64,
    pub output_sha256: String,
    pub probe: ProbeSummary,
}

/// What FFprobe reported about the produced file. Only measured values.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProbeSummary {
    pub container_format: String,
    pub video_codec: String,
    pub width: u32,
    pub height: u32,
    pub duration_ms: u64,
    pub video_streams: u32,
    pub audio_streams: u32,
}

/// The body of every non-2xx response.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorDocument {
    pub error: ErrorDetail,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ErrorDetail {
    /// Frozen token; see `ErrorCode::wire`.
    pub code: String,
    /// Fixed sentence. Never contains caller data, paths or subprocess output.
    pub message: String,
    /// Whether the caller may retry the same bytes.
    pub retryable: bool,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn health_document_advertises_the_bounds_the_code_enforces() {
        let health = crate::health_document("test-release", &crate::preset::DEMO_180P_V1);
        assert_eq!(health.limits.max_input_bytes, MAX_INPUT_BYTES);
        assert_eq!(health.limits.max_output_bytes, MAX_OUTPUT_BYTES);
        assert_eq!(health.limits.encode_deadline_ms, ENCODE_DEADLINE_MS);
        assert_eq!(health.limits.max_encode_threads, MAX_ENCODE_THREADS);
        assert_eq!(health.limits.max_concurrent_encodes, 1);
        assert_eq!(health.protocol, PROTOCOL_ID);
        assert_eq!(health.fixture, FIXTURE_ID);
        assert_eq!(health.presets, vec![crate::preset::DEMO_180P_V1.summary()]);
    }

    #[test]
    fn error_document_omits_the_operator_detail() {
        use crate::error::{ErrorCode, ProcessorError};
        let error = ProcessorError::new(ErrorCode::InvalidMedia)
            .with_detail("ffmpeg: /tmp/secret.mp4 - Invalid data found");
        let document = crate::error_document(&error);
        assert_eq!(document.error.code, "invalid_media");
        assert!(!document.error.retryable);
        // The body is assembled from fixed fields; the detail is not reachable.
        let rendered = serde_json::to_string(&document).unwrap();
        assert!(!rendered.contains("secret.mp4"), "{rendered}");
        assert!(!rendered.contains("ffmpeg"), "{rendered}");
    }
}
