// apps/backend/jobs/src/media_store.ts
//
// The private artifact store, as this Worker uses it: named fixtures in, encoded
// artifacts out, and nothing else.
//
// Why the keys are derived and never built from a request
// -------------------------------------------------------
// `fixtureKey` and `outputKey` are pure functions of a fixture identity, a job id
// and an attempt id. Nothing a caller controls reaches them. That is the property
// that makes it safe to hand a key to a second component — the maintenance sweep
// deletes by key — and it is what makes "which bytes does this key hold"
// answerable from a log line without storing a map.
//
// Every artifact key is **attempt-scoped**: `jobs/<jobId>/attempts/<attemptId>.mp4`.
// Two attempts of one job therefore write two different objects, and a late
// attempt cannot overwrite the bytes an earlier attempt committed. That is
// storage-level fencing to go with the repository's row-level fencing; the two
// protect different things, and either alone leaves a window.
//
// The ids are validated rather than escaped. A key is a path inside a bucket that
// a future reader will parse, and `..` in a key is a key that escapes the prefix
// the retention sweep reasons about.
//
// Bytes never pass through here as an array
// ------------------------------------------
// `putArtifact` takes a `ReadableStream` and returns a count and a hash. The
// alternative — read the body into an array, hash it, then upload — holds a
// 10 MiB artifact twice in a Worker's memory, and is the "materialize the video in
// a step result" failure this design forbids.

import { type JobFixture, MEDIA_KEY_PREFIX, mediaFixtureKey } from '@starter/schemas/jobs';
import { Sha256 } from './sha256.ts';
import { withKnownLength } from './stream.ts';

/**
 * Key prefix for everything in the bucket.
 *
 * Versioned from the first byte. A prefix means a future layout change is a new
 * prefix rather than a silent reinterpretation of objects whose bytes were written
 * under different assumptions.
 */
const PREFIX = MEDIA_KEY_PREFIX;

/** Identifiers allowed in a key. Deliberately narrow. */
const SAFE_ID = /^[A-Za-z0-9._-]{1,64}$/;

/** The private key of a named fixture. */
export const fixtureKey = mediaFixtureKey;

/**
 * The private key one attempt writes its output to.
 *
 * `attemptId` is validated with a wider charset than `jobId` because it is
 * generated by this repository (`createId('attempt')`) rather than chosen by a
 * user — but it is still validated, because "generated by us" is not a property a
 * reader of this file can check and a `..` in a key is a key outside the prefix.
 */
export const outputKey = (jobId: string, attemptId: string): string => {
  if (!SAFE_ID.test(jobId)) {
    throw new Error(`Refusing to build an artifact key: job id "${jobId}" is not a safe id.`);
  }
  if (!/^[A-Za-z0-9._-]{1,128}$/.test(attemptId) || attemptId.includes('..')) {
    throw new Error(
      `Refusing to build an artifact key: attempt id "${attemptId}" is not a safe id.`,
    );
  }
  return `${PREFIX}/jobs/${jobId}/attempts/${attemptId}.mp4`;
};

/** Largest input this Worker will read out of the bucket. Matches the processor. */
export const MAX_INPUT_BYTES = 5 * 1024 * 1024;

/** Largest output this Worker will write into the bucket. Matches the processor. */
export const MAX_OUTPUT_BYTES = 10 * 1024 * 1024;

/** What a bounded read reports about the object it read. */
export interface FixtureRead {
  key: string;
  /** Known before the body is consumed, so the request can declare a length. */
  bytes: number;
  stream: ReadableStream<Uint8Array>;
}

/** What a streamed write reports back. */
export interface ArtifactWrite {
  key: string;
  /** Bytes the storage accepted. Not the bytes we hoped to send. */
  bytes: number;
  /** SHA-256 of exactly those bytes, computed while they streamed. */
  sha256: string;
}

/**
 * The artifact storage this Worker needs.
 *
 * Two implementations exist: this one, and nothing else. It is an interface
 * because the unit lane asserts key derivation and hashing without a bucket, and
 * because `purgeExpiredArtifacts` in `@starter/jobs` states the same two questions
 * (`isRemoved`) without naming a provider.
 */
export interface MediaStore {
  /** The named fixture, or null when it is genuinely absent. Never optimistic. */
  readFixture(fixture: JobFixture, maxBytes: number): Promise<FixtureRead | null>;
  /** Stream an encoded artifact to its attempt-scoped key. */
  putArtifact(
    jobId: string,
    attemptId: string,
    stream: ReadableStream<Uint8Array>,
    expectedBytes: number,
  ): Promise<ArtifactWrite>;
  /** Existence and size, or null. */
  head(key: string): Promise<{ bytes: number } | null>;
  /** Remove bytes. Idempotent: an absent object is not an error. */
  delete(key: string): Promise<void>;
  /** True only when the object is genuinely absent. */
  isRemoved(key: string): Promise<boolean>;
}

/**
 * Wrap a stream so its bytes are counted and hashed on the way past.
 *
 * A `TransformStream` rather than a tee-and-collect: collecting would hold the
 * artifact in memory, which is the thing this file exists to avoid. The hash is
 * computed incrementally (`./sha256.ts`) because `crypto.subtle.digest` is
 * one-shot and the whole buffer is what we refuse to hold.
 *
 * `exceeded` is checked *before* the chunk is forwarded, so an over-ceiling
 * producer fails the write instead of uploading bytes past the bound and
 * discovering the size afterwards.
 */
const countingHashStream = (
  stream: ReadableStream<Uint8Array>,
  onChunk: (total: number) => void,
): { stream: ReadableStream<Uint8Array>; hex: () => string } => {
  const hash = new Sha256();
  let total = 0;
  const piped = stream.pipeThrough(
    new TransformStream<Uint8Array, Uint8Array>({
      transform: (chunk, controller) => {
        total += chunk.byteLength;
        onChunk(total);
        hash.update(chunk);
        controller.enqueue(chunk);
      },
    }),
  );
  return { stream: piped, hex: () => hash.hex() };
};

export const createMediaStore = (
  bucket: R2Bucket,
  maxOutputBytes = MAX_OUTPUT_BYTES,
): MediaStore => ({
  async readFixture(fixture, maxBytes) {
    const key = fixtureKey(fixture);
    // A plain `get`, not a conditional one with `onlyIf`.
    //
    // The conditional read looked better — it turns "absent" into a null rather than
    // a thrown error — and it is wrong: the local runtime hands back an R2 object
    // whose `body` yields *zero* bytes, so the encode request that forwards it
    // arrives at the processor as an empty body and is refused with
    // `input_empty`. The compute lane is what found this; the symptom (a terminal
    // `invalid_media`-shaped failure on a perfectly good fixture) points nowhere
    // near a conditional read.
    //
    // `head` is the cheap existence check, and it is available below for exactly
    // that; this path wants the body anyway, so it reads the object once and treats
    // a null as the truth it is.
    const object = await bucket.get(key);
    if (object === null) {
      return null;
    }
    if (object.size > maxBytes) {
      // Refusing here rather than truncating: a truncated MP4 is a file FFmpeg
      // will happily decode into a shorter video, which is a *successful* encode
      // of the wrong thing.
      throw new Error(
        `Fixture ${key} is ${object.size} bytes, over the ${maxBytes}-byte input ceiling.`,
      );
    }
    return { key, bytes: object.size, stream: object.body as ReadableStream<Uint8Array> };
  },

  async putArtifact(jobId, attemptId, stream, expectedBytes) {
    const key = outputKey(jobId, attemptId);
    if (expectedBytes > maxOutputBytes) {
      throw new Error(
        `Refusing to store ${expectedBytes} bytes at ${key}: the ceiling is ${maxOutputBytes}.`,
      );
    }

    const hashed = countingHashStream(stream, (total) => {
      if (total > maxOutputBytes) {
        throw new Error(
          `The processor produced more than the ${maxOutputBytes}-byte output ceiling.`,
        );
      }
    });

    // One pass: the hash is fed inside the transform rather than by re-reading the
    // stored object, so nothing is uploaded twice and nothing is held in memory.
    // The declared length is the processor's own reported size, so this is a check as
    // well as a declaration: a body that is shorter or longer fails the upload here,
    // before a truncated object can be committed as somebody's result.
    const stored = await bucket.put(key, withKnownLength(hashed.stream, expectedBytes), {
      httpMetadata: { contentType: 'video/mp4' },
    });

    return { key, bytes: stored?.size ?? 0, sha256: hashed.hex() };
  },

  async head(key) {
    const object = await bucket.head(key);
    return object === null ? null : { bytes: object.size };
  },

  async delete(key) {
    // Idempotent by construction: deleting an absent key is a no-op in R2, and a
    // sweep that treated "already gone" as an error would fail forever on the
    // second run of the same slot.
    await bucket.delete(key);
  },

  async isRemoved(key) {
    return (await bucket.head(key)) === null;
  },
});
